# Generated by Django 3.2.12 on 2023-02-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0002_alter_farmers_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cultures',
            new_name='Culture',
        ),
        migrations.RenameModel(
            old_name='Farmers',
            new_name='Farmer',
        ),
        migrations.RenameModel(
            old_name='Plots',
            new_name='Plot',
        ),
        migrations.RenameModel(
            old_name='Seasons',
            new_name='Season',
        ),
    ]
